# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{rstake}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Rico Sta. Cruz", "Sinefunc, Iinc."]
  s.date = %q{2010-11-17}
  s.default_executable = %q{rstake}
  s.description = %q{Watches a list of files for changes, and executes a given command when any changes are detected.}
  s.email = %q{rico@sinefunc.com}
  s.executables = ["rstake"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.md"
  ]
  s.files = [
    ".gitignore",
     "LICENSE",
     "README.md",
     "Rakefile",
     "VERSION",
     "bin/rstake",
     "lib/rstake.rb",
     "lib/rstake/app.rb",
     "lib/rstake/growl_notifier.rb",
     "lib/rstake/print_notifier.rb",
     "lib/rstake/watcher.rb",
     "rstake.gemspec"
  ]
  s.homepage = %q{http://github.com/sinefunc/rstake}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Watch a directory for changes.}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<growl>, [">= 1.0.3"])
    else
      s.add_dependency(%q<growl>, [">= 1.0.3"])
    end
  else
    s.add_dependency(%q<growl>, [">= 1.0.3"])
  end
end

